# 用于构建并部署 Jekyll 网站到 GitHub Pages 的示例工作流
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
# 当推送到默认分支时运行
  push:
    branches: ["master"]

# 允许你从 Actions 标签页手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在进行的和最新排队之间的队列。
# 但不要取消正在进行的运行，以确保生产部署可以完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出代码
        uses: actions/checkout@v4
      - name: Setup Pages # 配置 Pages 环境
        uses: actions/configure-pages@v5
      - name: Build with Jekyll # 使用 Jekyll 构建
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact # 上传构建产物
        uses: actions/upload-pages-artifact@v3

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages # 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
